### ISSUE TITLE
RubyDelay

### ISSUE THREAD

**Issue by ghost** [thbar/opaz-plugdk#2]
Hi thbar,

RubyDelay is a bit buggy and needs the following changes:

-Line 214 should be: @echoLFODiff = @echoLFODiffMax \* (1.0 + Math.sin(@echoLFOPos))

-Line 192 should be: if (echoRead >= @echoSize-1)

-Line 62 should be: @echo = Array.new(@echoSize){|i| 0.0} unless @echo.size == @echoSize

I think it should work okay then..

**Comment by thbar** [comment]
Hi caco!

I just pushed your modifications back. This one is seriously buggy, it was mostly a try to port things but it never made til the end so far.

It doesn't seem to really work on my machine. Does it work for you ?

Thanks for your patch!

-- Thibaut
